//HintName: ToolDefinitionAttribute.g.cs
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by the Dev.Tools.CodeAnalysis.Generators.ToolsDefinitionGenerator.
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace Dev.Tools;

[AttributeUsage(AttributeTargets.Class)]
internal sealed class ToolDefinitionAttribute : System.Attribute
{
    public string Name { get; set; } = default!;
    public string[] Aliases { get; set; } = [];
    public string[] Categories { get; set; } = [];
    public string[] Keywords { get; set; } = [];
    public string[] ErrorCodes { get; set; } = [];
}

public readonly record struct ToolDefinition
(
    string Name,
    string[] Aliases,
    string[] Categories,
    string[] Keywords,
    string[] ErrorCodes,
    Type ToolType
);