//HintName: Category_GetValues.g.cs
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated at 1/1/2025 12:00:00 AM by the Dev.Tools.CodeAnalysis.Generators.ValuesListGenerator.
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
#nullable enable

namespace Dev.Tools;

public partial record struct Category
{
    public static IEnumerable<string> GetValues()
    {
        return new List<string> { "None", "Converter" };
    }
}