//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Tools.Web.Locals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dev.Tools.Web.Locals.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode base64 representation into string.
        /// </summary>
        internal static string Base64DecoderTool_Description {
            get {
                return ResourceManager.GetString("Base64DecoderTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 Decoder.
        /// </summary>
        internal static string Base64DecoderTool_Title {
            get {
                return ResourceManager.GetString("Base64DecoderTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode strings into their base64 representation.
        /// </summary>
        internal static string Base64EncoderTool_Description {
            get {
                return ResourceManager.GetString("Base64EncoderTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 Encoder.
        /// </summary>
        internal static string Base64EncoderTool_Title {
            get {
                return ResourceManager.GetString("Base64EncoderTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert date and time into the various different formats.
        /// </summary>
        internal static string DateTimeConverterTool_Description {
            get {
                return ResourceManager.GetString("DateTimeConverterTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime Converter.
        /// </summary>
        internal static string DateTimeConverterTool_Title {
            get {
                return ResourceManager.GetString("DateTimeConverterTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash a text string using the different functions.
        /// </summary>
        internal static string HashTextTool_Description {
            get {
                return ResourceManager.GetString("HashTextTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Text.
        /// </summary>
        internal static string HashTextTool_Title {
            get {
                return ResourceManager.GetString("HashTextTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide IP address details.
        /// </summary>
        internal static string IpDetailsTool_Description {
            get {
                return ResourceManager.GetString("IpDetailsTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Details.
        /// </summary>
        internal static string IpDetailsTool_Title {
            get {
                return ResourceManager.GetString("IpDetailsTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Locals_uk_Title {
            get {
                return ResourceManager.GetString("Locals_uk_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        internal static string Locals_us_Title {
            get {
                return ResourceManager.GetString("Locals_us_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random memoizable Passphrases.
        /// </summary>
        internal static string PassphraseGeneratorTool_Description {
            get {
                return ResourceManager.GetString("PassphraseGeneratorTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase Generator.
        /// </summary>
        internal static string PassphraseGeneratorTool_Title {
            get {
                return ResourceManager.GetString("PassphraseGeneratorTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random string with the chars you want, uppercase or lowercase letters, numbers and/or symbols..
        /// </summary>
        internal static string TokenGeneratorTool_Description {
            get {
                return ResourceManager.GetString("TokenGeneratorTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Generator.
        /// </summary>
        internal static string TokenGeneratorTool_Title {
            get {
                return ResourceManager.GetString("TokenGeneratorTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random Universally Unique Lexicographically Sortable Identifier (ULID)..
        /// </summary>
        internal static string UlidGeneratorTool_Description {
            get {
                return ResourceManager.GetString("UlidGeneratorTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULID Generator.
        /// </summary>
        internal static string UlidGeneratorTool_Title {
            get {
                return ResourceManager.GetString("UlidGeneratorTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Universally Unique Identifier (UUID) is a 128-bit number used to identify information in computer systems. .
        /// </summary>
        internal static string UuidGeneratorTool_Description {
            get {
                return ResourceManager.GetString("UuidGeneratorTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID Generator.
        /// </summary>
        internal static string UuidGeneratorTool_Title {
            get {
                return ResourceManager.GetString("UuidGeneratorTool_Title", resourceCulture);
            }
        }
    }
}
