using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Dev.Tools.Generators.Core;

public record CodeBlock
{
    private string? _shortName;
    public string Namespace { get; set; } = default!;

    public string TypeName { get; set; } = default!;

    public string Content { get; set; } = default!;

    public Type? GeneratorType { get; set; }

    public string OutputFileName => $"{TypeName}.g.cs";

    public string TypeFullName => $"{Namespace}.{TypeName}";

    public Dictionary<string, string> Placeholders { get; set; } = new();

    public string? Header { get; set; }

    public string SyntaxTypeName
    {
        get => _shortName ?? TypeName;
        set => _shortName = value;
    }

    public static implicit operator SourceText(CodeBlock codeBlock)
        => SourceText.From(codeBlock.ToString(), Encoding.UTF8);

    public static implicit operator SyntaxTree(CodeBlock codeBlock)
        => CSharpSyntaxTree.ParseText(codeBlock.ToString());

    public override string ToString()
    {
        var code =
            $"""
             {GetHeader()}
             namespace {Namespace};

             {BuildContent()}
             """;

        return code;
    }

    private string BuildContent()
    {
        var replacements = Placeholders
            .Concat(new Dictionary<string, string>
            {
                [nameof(Namespace)] = Namespace,
                [nameof(TypeName)] = TypeName,
                [nameof(TypeFullName)] = TypeFullName,
            });

        var builder = new StringBuilder(Content);
        foreach (var token in replacements)
        {
            builder.Replace($"{{{token.Key}}}", token.Value);
        }

        return builder.ToString();
    }

    private string GetHeader() =>
        Header ??
        $"""
         //------------------------------------------------------------------------------ 
         // <auto-generated> 
         // This code was generated by the {GeneratorType?.FullName ?? "generator"}.
         // 
         // Changes to this file may cause incorrect behavior and will be lost if 
         // the code is regenerated. 
         // </auto-generated> 
         //------------------------------------------------------------------------------

         """;
}