//HintName: ToolProvider.g.cs
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by the Dev.Tools.Generators.ToolDefinitionGenerator.
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace Dev.Tools;

public partial class ToolProvider
{
    protected IEnumerable<ToolDefinition> GetToolDefinitions()
    {
        yield return new ToolDefinition(
            Name: "tool-test",
            Aliases: ["tt"],
            Categories: ["default"],
            Keywords: ["test", "keywords"],
            ErrorCodes: ["unknown"],
            ToolType: typeof(Dev.Tools.TestTool)
        );

    }
}
