//HintName: ToolDefinitionAttribute.g.cs
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by the Dev.Tools.Generators.ToolDefinitionGenerator.
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace Dev.Tools;

[AttributeUsage(AttributeTargets.Class)]
public sealed class ToolDefinitionAttribute : Attribute
{
    public string Name { get; set; } = default!;
    public string[] Aliases { get; set; } = [];
    public string[] Categories { get; set; } = [];
    public string[] Keywords { get; set; } = [];
    public string[] ErrorCodes { get; set; } = [];
}
