//HintName: GenerateValuesAttribute.g.cs
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by the Dev.Tools.Generators.ValuesListGenerator.
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace Dev.Tools;

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
public class GenerateValuesAttribute: System.Attribute;
