//HintName: ToolsProvider.g.cs
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by the Dev.Tools.CodeAnalysis.Generators.ToolsDefinitionGenerator.
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
#nullable enable

namespace Dev.Tools.Providers;

internal partial class ToolsProvider
{
    private IReadOnlyCollection<ToolDefinition>? _tools;
      
    public IReadOnlyCollection<ToolDefinition> GetToolDefinitions()
    {
        return _tools ??= [
            new ToolDefinition(
                Name: "tool-test",
                Aliases: ["tt"],
                Categories: ["default"],
                Keywords: ["test", "keywords"],
                ErrorCodes: ["unknown"],
                ToolType: typeof(Dev.Tools.TestTool)
            ),

        ];
    }
}