//HintName: ToolDefinitionAttribute.g.cs
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated at 1/1/2025 12:00:00 AM by the Dev.Tools.CodeAnalysis.Generators.ToolsCatalogGenerator.
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
#nullable enable
using System;

namespace Dev.Tools;

[AttributeUsage(AttributeTargets.Class)]
internal sealed class ToolDefinitionAttribute : Attribute
{
    public required string Name { get; set; }
    public string[] Aliases { get; set; } = [];
    public Category[] Categories { get; set; } = [];
    public Keyword[] Keywords { get; set; } = [];
}