//HintName: ToolDefinition.g.cs
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated at 1/1/2025 12:00:00 AM by the Dev.Tools.CodeAnalysis.Generators.ToolsCatalogGenerator.
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
#nullable enable

namespace Dev.Tools;

public sealed record ToolDefinition
(
    string Name,
    string[] Aliases,
    Category[] Categories,
    Keyword[] Keywords,
    string[] ErrorCodes,
    Type ToolType,
    ToolTypeDetails ArgsType,
    ToolTypeDetails ReturnType
);

public sealed record ToolTypeDetails(
  Type DataType,
  ToolTypeProperty[] Properties
);

public sealed record ToolTypeProperty(string Name, Type PropertyType, bool IsRequired, bool IsNullable);