//HintName: ToolsCatalog.g.cs
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated at 1/1/2025 12:00:00 AM by the Dev.Tools.CodeAnalysis.Generators.ToolsCatalogGenerator.
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Generic;

namespace Dev.Tools;

internal class ToolsCatalog
{
    public static IReadOnlyCollection<ToolDefinition> ToolDefinitions { get; } = 
    [
        new ToolDefinition(
            Name: "tool-test",
            Aliases: ["tt"],
            Categories: ["default"],
            Keywords: ["test", "keywords"],
            ErrorCodes: [ErrorCode.Unknown, "testCode", Errors.TextEmpty],
            ToolType: typeof(Dev.Tools.TestTool),
            ArgsType: new ToolTypeDetails(
                DataType: typeof(int),
                Properties: [
                    
                ]
            ),
            ReturnType: new ToolTypeDetails(
                DataType: typeof(long),
                Properties: [
                    
                ]
            )   
        ),

    ];
}